title: "Zir"
description: "Personal blog"
url: "https://zir.is-a.dev"
baseurl: ""

theme: minima

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

paginate: 6
paginate_path: "/blog/page:num/"

# Buat post otomatis di /blog/:title/
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /blog/:title/
